
[secrets]
folder = "C:/Alex/Code/ea-journeys/secrets"

[knowledge-base]
knowledge-base-root-folder = "C:/Users/aleja/Documents/Code/chateauclaudia-labs/apodeixi/test_db/knowledge-base"
external-collaboration-folder = "C:/Users/aleja/Documents/Code/chateauclaudia-labs/apodeixi/test_db/share-point"

[organization-settings]
month-fiscal-year-starts = 6

# ------------------------------------- Corporate Banking Products
[products.corporate]
name                = "Corporate"
[products.corporate.liq]
short-name          = "LIQ"
name                = "Loan IQ"
[products.corporate.ccb]
short-name          = "CCB"
name                = "Connected Corporate Banking"
[products.corporate.fcc]
short-name          = "FCC"
name                = "Fusion Corporate Channels"
[products.corporate.fcm]
short-name          = "FCM"
name                = "Fusion Cash Management"
[products.corporate.ti]
short-name          = "TI"
name                = "Trade Innovation"

# ------------------------------------- Retail International Products
[products.retail-international]
name                = "Retail International"
[products.retail-international.ess]
short-name          = "ESS"
name                = "Essence"

# ------------------------------------- Payments Products
[products.payments]
name                = "Payments"
[products.payments.gpp]
short-name          = "GPP"
name                = "Global PayPlus"

# ------------------------------------- NACM & Digital Products
[products.nacm-and-digital]
name                = "NACM & Digital"
[products.nacm-and-digital.fcq]
short-name          = "FCQ"
name                = "Credit Quest"
[products.nacm-and-digital.lpr]
short-name          = "LPR"
name                = "Laser Pro"
[products.nacm-and-digital.mbtlos]
short-name          = "MBTLOS"
name                = "MortgageBot LOS"
[products.nacm-and-digital.mbtpos]
short-name          = "MBTPOS"
name                = "MortgageBot POS"
[products.nacm-and-digital.mlz]
short-name          = "MLZ"
name                = "Malauzai"
[products.nacm-and-digital.phx]
short-name          = "PHX"
name                = "Phoenix"

# ------------------------------------- TCM Products
[products.tcm]
name                = "Trade & Capital Markets"
[products.tcm.kon]
short-name          = "KON"
name                = "Kondor"
[products.tcm.opi]
short-name          = "OPI"
name                = "Opics"
[products.tcm.risk]
short-name          = "RISK"
name                = "Risk"
[products.tcm.sum]
short-name          = "SUM"
name                = "Summit"

