test_create_environment_ENV:
  excel-postings:
    journeys:
      Dec 2020:
        FusionOpus:
          Default:
            _ARCHIVE:
              (Timestamp omitted) Posting:
                POST_EVENT_LOG.txt: '

                  Size (in bytes):  2382

                  '
                test_create_environment_big-rocks.journeys.a6i.xlsx: '

                  Size (in bytes):  25146

                  '
  manifests:
    my-corp.production:
      modernization.default.dec-2020.fusionopus:
        big-rock-estimate.1.yaml: '

          Size (in bytes):  1272

          '
        big-rock.1.yaml: '

          Size (in bytes):  1426

          '
        investment.1.yaml: '

          Size (in bytes):  1320

          '
