apiVersion: account.mock.a6i.io/v1
assertion:
  asset-class:
    AC1:
      FDIC Insurance: 'No'
      Institution:
        I1:
          Account:
            A1:
              Currency: USD
              UID: AC1.I1.A1
              name: IRA xxx435
            A1-name: IRA xxx435
            A2:
              Currency: USD
              UID: AC1.I1.A2
              name: CMA xxx832
            A2-name: CMA xxx832
          State: MA
          UID: AC1.I1
          Zipcode: 21340
          name: Fidelity Investments
        I1-name: Fidelity Investments
        I2:
          Account:
            A1:
              Currency: GBP
              UID: AC1.I2.A1
              name: IRA xxx2954
            A1-name: IRA xxx2954
            A2:
              Currency: USD
              UID: AC1.I2.A2
              name: Mutual Funds xxx972
            A2-name: Mutual Funds xxx972
          State: DEL
          UID: AC1.I2
          Zipcode: 43987
          name: Vanguard
        I2-name: Vanguard
      Taxable to non Residents: 'Yes'
      UID: AC1
      name: Brokerage
    AC1-name: Brokerage
    AC2:
      FDIC Insurance: 'Yes'
      Institution:
        I1:
          Account:
            A1:
              Currency: USD
              UID: AC2.I1.A1
              name: Savings xxx777
            A1-name: Savings xxx777
            A2:
              Currency: EUR
              UID: AC2.I1.A2
              name: Checking xxx893
            A2-name: Checking xxx893
          State: CA
          UID: AC2.I1
          Zipcode: 94721
          name: Bank of America
        I1-name: Bank of America
        I2:
          Account:
            A1:
              Currency: USD
              UID: AC2.I2.A1
              name: CD xxx621
            A1-name: CD xxx621
            A2:
              Currency: USD
              UID: AC2.I2.A2
              name: Savings xxx982
            A2-name: Savings xxx982
            A3:
              Currency: USD
              UID: AC2.I2.A3
              name: Checking xxx999
            A3-name: Checking xxx999
          State: OR
          UID: AC2.I2
          Zipcode: 65321
          name: Bank of Seattle
        I2-name: Bank of Seattle
      Taxable to non Residents: 'No'
      UID: AC2
      name: Banking
    AC2-name: Banking
  entity_type: Asset Class
  estimatedBy: joe.thetestlead@mycorp.com
  estimatedOn: &id001 2021-06-26 00:00:00
  recordedBy: jill.thesprintmaster@mycorp.com
  testCase: user_validation_0
  testDescription: Baseline case - no malformed input from user
  testFamily: Test_MalformedInput
kind: properties
metadata:
  labels:
    environment: Production
    estimatedBy: joe.thetestlead@mycorp.com
    estimatedOn: *id001
    organization: My Corp
    recordedBy: jill.thesprintmaster@mycorp.com
    testCase: user_validation_0
    testFamily: Test_MalformedInput
    version: 1
  name: test_malformedinput.user_validation_0
  namespace: my-corp.production
  version: 1
