apiVersion: account.mock.a6i.io/v1
assertion:
  asset-class:
    AC1:
      Institution:
        I1:
          Account:
            A1:
              UID: AC1.I1.A1
              name: IRA xxx435
            A1-name: IRA xxx435
            A2:
              UID: AC1.I1.A2
              name: CMA xxx832
            A2-name: CMA xxx832
          UID: AC1.I1
          name: Fidelity Investments
        I1-name: Fidelity Investments
        I2:
          Account:
            A1:
              UID: AC1.I2.A1
              name: IRA xxx2954
            A1-name: IRA xxx2954
            A2:
              UID: AC1.I2.A2
              name: Mutual Funds xxx972
            A2-name: Mutual Funds xxx972
          UID: AC1.I2
          name: Vanguard
        I2-name: Vanguard
      UID: AC1
      name: Brokerage
    AC1-name: Brokerage
    AC2:
      Institution:
        I1:
          Account:
            A1:
              UID: AC2.I1.A1
              name: Savings xxx777
            A1-name: Savings xxx777
            A2:
              UID: AC2.I1.A2
              name: Checking xxx893
            A2-name: Checking xxx893
          UID: AC2.I1
          name: Bank of America
        I1-name: Bank of America
        I2:
          Account:
            A1:
              UID: AC2.I2.A1
              name: CD xxx621
            A1-name: CD xxx621
            A2:
              UID: AC2.I2.A2
              name: Savings xxx982
            A2-name: Savings xxx982
            A3:
              UID: AC2.I2.A3
              name: Checking xxx999
            A3-name: Checking xxx999
          UID: AC2.I2
          name: Bank of Seattle
        I2-name: Bank of Seattle
      UID: AC2
      name: Banking
    AC2-name: Banking
  entity_type: Asset Class
  estimatedBy: joe.thetestlead@mycorp.com
  estimatedOn: &id001 2021-06-26 00:00:00
  recordedBy: jill.thesprintmaster@mycorp.com
  testCase: user_validation_10
  testDescription: 'User left blank the entity name in a row with data for that entity,
    and the software can ''correct it'' if what happened is that the user entered
    it in the previous row and then left the previous row blank starting at some column,
    using the next row insted for such data. This is the second of two sub-cases:


    the extra row data is for the next interval after the one with the missing entity
    name'
  testFamily: Test_MalformedInput
kind: hierarchy
metadata:
  labels:
    estimatedBy: joe.thetestlead@mycorp.com
    estimatedOn: *id001
    knowledgeBase: Production
    organization: My Corp
    recordedBy: jill.thesprintmaster@mycorp.com
    testCase: user_validation_10
    testFamily: Test_MalformedInput
    version: 1
  name: test_malformedinput.user_validation_10
  namespace: my-corp.production
  version: 1
