static_data_flows.products.products_ENV:
  external-collaboration:
    admin:
      static-data:
        _ARCHIVE:
          (Timestamp omitted) Posting:
            FORM_REQUEST_EVENT_LOG.txt: '

              Size (in bytes):  366

              '
            POST_EVENT_LOG.txt: '

              Size (in bytes):  1728

              '
            products.static-data.admin.a6i.xlsx: '

              Size (in bytes):  7131

              '
    journeys:
      Dec 2020:
        FusionOpus:
          Default:
            OPUS_big-rocks.journeys.a6i.xlsx: '

              Size (in bytes):  25146

              '
        LedgerPro:
          OfficialPlan:
            LedgerPro.big-rocks.journeys.a6i.xlsx: '

              Size (in bytes):  28512

              '
  kb:
    excel-postings:
      admin:
        static-data:
          _ARCHIVE:
            (Timestamp omitted) Posting:
              FORM_REQUEST_EVENT_LOG.txt: '

                Size (in bytes):  366

                '
              POST_EVENT_LOG.txt: '

                Size (in bytes):  1728

                '
              products.static-data.admin.a6i.xlsx: '

                Size (in bytes):  7131

                '
          products.static-data.admin.a6i.xlsx: '

            Size (in bytes):  7131

            '
    manifests:
      my-corporation.testing-area:
        static-data:
          line-of-business.1.yaml: '

            Size (in bytes):  800

            '
          product.1.yaml: '

            Size (in bytes):  1039

            '
