test_create_environment_ENV:
  external-collaboration:
    journeys:
      Dec 2020:
        FusionOpus:
          Default:
            OPUS_big-rocks.journeys.a6i.xlsx: '

              Size (in bytes):  25163

              '
