package:
  name: apodeixi
  version: 0.2.0a9 

source:

  git_rev: v0.2.0a9
  git_url: https://github.com/ChateauClaudia-Labs/apodeixi.git

requirements:
  build: # Make sure to include both what is needed to build and to run. Else will get build errors
    - python >=3.9
    - pandas >=1.2.4
    - openpyxl >=3.0.7
    - pyyaml >=5.4.1
    - xlsxwriter >=1.3.8
    - nltk >=3.6.1
    - setuptools >=42
    - wheel
    - twine >=3.4.1
    - notebook >=6.4.0

  run: # Include any dependencies that the user should be prompted to also install when installing our package
    - python >=3.9
    - pandas >=1.2.4
    - openpyxl >=3.0.7
    - pyyaml >=5.4.1
    - xlsxwriter >=1.3.8
    - nltk >=3.6.1
    - notebook >=6.4.0
    

test:
  imports: # Never leave this as "None", as build will fail (at least for default configuration)
    - unittest

about:
  home: