{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: apodeixi
  version: {{ data.get('version') }}

source:

  git_rev: {{ "v" + data.get('version') }}
  git_url: https://github.com/ChateauClaudia-Labs/apodeixi.git

requirements:
  build: # Make sure to include both what is needed to build and to run. Else will get build errors
    - python >=3.9.6
    - pandas >=1.3.1
    - openpyxl >=3.0.7
    - pyyaml >=5.4.1
    - xlsxwriter >=3.0.1
    - nltk >=3.6.1
    - setuptools >=52.0.0
    - jinja2 >=2.11.3
    - wheel >=0.37.0
    - twine >=3.4.1
    - notebook >=6.4.2
    - conda-build >=3.21.4
    - toml >=0.10.2
    - click >=8.0.1
    - tabulate >=0.8.9

  run: # Include any dependencies that the user should be prompted to also install when installing our package
    - python >=3.9.6
    - pandas >=1.3.1
    - openpyxl >=3.0.7
    - pyyaml >=5.4.1
    - xlsxwriter >=3.0.1
    - jinja2 >=2.11.3
    - nltk >=3.6.1
    - notebook >=6.4.2
    - toml >=0.10.2
    - click >=8.0.1
    - tabulate >=0.8.9
    

test:
  imports: # Never leave this as "None", as build will fail (at least for default configuration)
    - unittest

about:
  home: