package:
  name: apodeixi
  version: 0.2.0a2 # Make sure this is the version already uploaded to PyPI

source:

  git_rev: v0.2.0a2
  git_url: https://github.com/ChateauClaudia-Labs/apodeixi.git

requirements:
  build:
    - python >=3.9
    - pandas >=1.2.4
    - openpyxl >=3.0.7
    - pyyaml >=5.4.1
    - xlsxwriter >=1.3.8
    - nltk >=3.6.1
    - setuptools >=42
    - wheel
    - twine >=3.4.1

  run:
    - python >=3.9
    - pandas >=1.2.4
    - openpyxl >=3.0.7
    - pyyaml >=5.4.1
    - xlsxwriter >=1.3.8
    - nltk >=3.6.1
    

test:
  imports:
    - unittest

about:
  home: